<?php

namespace App;

use App\Amount;
use Carbon\Carbon;
use ErrorException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use NumberFormatter;

class Transaction extends Model
{
    public $timestamps = false;

    /**
     * The ID of the Transaction on Up.
     *
     * @var string
     */
    protected $upid;

    /**
     * Category
     *
     * @var string
     */
    protected $category;

    /**
     * Value of the transaction
     *
     * @var App\Amount
     */
    protected $amount;

    /**
     * Timestamp the transaction was created
     *
     * @var string
     */
    protected $createdAt;

    /**
     * Timestamp the transaction was settled
     *
     * @var string
     */
    protected $settledAt;

    /**
     * Description generated by Up (e.g. Salsa's Fresh Mex Grill when actual message might be NET.DB SYSTEMS PTY Q,DOCKLANDS)
     *
     * @var string
     */
    protected $description;

    /**
     * Raw transaction text received by Up (e.g. NET.DB SYSTEMS PTY Q,DOCKLANDS)
     *
     * @var string
     */
    protected $rawText;

    /**
     * Status (e.g. SETTLED/PENDING)
     *
     * @var string
     */
    protected $status;

    /**
     * Raw JSON of transaction as provided by Up API
     *
     * @var string
     */
    protected $rawTransaction;

    /* Default values of Attributes */
    protected $attributes = [
        "createdAt" => "",
        "settledAt" => "",
        "status" => "PENDING"
    ];

    /* Fields allowed to be populated by fill() in fromUpTransaction */
    protected $fillable = [
        "upid",
        "category",
        "createdAt",
        "settledAt",
        "description",
        "rawText",
        "status"
    ];

    /**
     * Build a Transaction from the JSON received from the Up API
     * 
     * @param object $upTransaction JSON object as received from Up API 
     * @return App\Transaction
     */
    public static function fromUpTransaction($upTransaction)
    {
        Log::debug("Creating Transaction from " . json_encode($upTransaction));
        $instance = new self();
        $instance->rawTransaction = $upTransaction;
        $instance->upid = $upTransaction->id;
        $instance->fill((array)$upTransaction->attributes);
        $instance->amount = new Amount((array)$upTransaction->attributes->amount);
        try {
            $instance->category = $upTransaction->relationships->category->data->id;
        } catch(ErrorException $e) {
            $instance->category = null;
        }
        return $instance;
    }

    public function getTimestampAttribute() {
        return Carbon::parse($this->createdAt);
    }

    public function getDateAttribute() {
        return $this->timestamp->format('D M jS');
    }

    public function getTimeAttribute() {
        return $this->timestamp->format('g:i A');
    }

    public function getAmountFormattedAttribute() {
        $fmt = new NumberFormatter(app()->getLocale(), NumberFormatter::CURRENCY);
        $amt = $this->attributes["amount"];
        return $fmt->formatCurrency($amt->valueInBaseUnits/100.0, $amt->currencyCode);
    }

    public function getDebitCreditAttribute() {
        return ($this->attributes["amount"]->valueInBaseUnits<0)?'debit':'credit';
    }
}
